services:
  
  ecommerce-mysql:
    platform: linux/x86_64
    build: ${ECOMMERCE_SERVICE_PATH}/Docker/database/.
    restart: always
    container_name: ${ECOMMERCE_MYSQL_NAME}

    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${ECOMMERCE_MYSQL_DATABASE}
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password

    ports:
      - ${ECOMMERCE_MYSQL_PORT}:3306

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  ecommerce-app:
    build: ${ECOMMERCE_SERVICE_PATH}/Docker/app/.
    container_name: ${ECOMMERCE_SERVICE_NAME}
    command: ["npm", "run", "dev"]

    env_file:
      - .env

    environment:
      - SEQUELIZE_HOST=${ECOMMERCE_MYSQL_NAME}
      - SEQUELIZE_DATABASE=${ECOMMERCE_MYSQL_DATABASE}

    volumes:
      - ${ECOMMERCE_SERVICE_PATH}/src:/app/src
      - ${ECOMMERCE_SERVICE_PATH}/tests:/app/tests
      - ${ECOMMERCE_SERVICE_PATH}/Docker/database/firestore-account:/app/firestore-account

    ports:
      - ${ECOMMERCE_APP_PORT}:8080

    depends_on:
      ecommerce-mysql:
        condition: service_healthy